services:
  db:
    image: postgres:14.1-alpine
    env_file: ./.env
    environment:
      - PGUSER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    depends_on:
      db:
        condition: service_healthy
    build: ./delivery-engine
    env_file: ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_BASIC_ENABLED=false
    ports:
      - $SPRING_PORT:8080
    restart: on-failure
