# This is a basic workflow to help you get started with Actions

name: Continuous integration - Staging Environment

# Controls when the workflow will run
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to staging environment
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          printf "\nSPRING_PORT=8081"
          docker-compose down -v
          docker-compose build
          docker-compose up -d
